services:
  # ===== AMD64 =====
  nav2:
    build: .
    image: cuda12.9.1:humble-uv-nvm
    container_name: nav2
    privileged: true
    tty: true
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/root/nav2
      - /tmp/.X11-unix:/tmp/.X11-unix

  nav2-gpu:
    extends:
      service: nav2
    container_name: nav2-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute, graphics]
    profiles:
      - gpu

  # ===== Jetson ARM64 =====
  nav2-jetson:
    build:
      args:
        BASE_IMAGE: dustynv/cudnn:8.9-r36.2.0
    image: cudnn8.9-jetson:humble-uv-nvm
    container_name: nav2-jetson
    runtime: nvidia
    privileged: true
    tty: true
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/root/.Xauthority
    volumes:
      - .:/root/nav2
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/argus_socket:/tmp/argus_socket
      - ~/.Xauthority:/root/.Xauthority
    profiles:
      - jetson